name: WIP:Run tests automatically on push

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  run-ui-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        if: ${{ success() }}
        run: |
          python3 -m pip install --user poetry

      - name: Install Homebrew (macOS)
        if: matrix.os == 'macos-latest' && success()
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Allure (Linux)
        if: matrix.os == 'ubuntu-latest' && success()
        run: |
          sudo apt-get update
          sudo apt-get install allure

      - name: Install Allure (macOS)
        if: matrix.os == 'macos-latest' && success()
        run: |
          brew install allure

      - name: Install project dependencies
        if: ${{ success() }}
        run: |
          poetry install

      - name: Verify Poetry installation
        if: ${{ success() }}
        run: |
          poetry --version

      - name: Run tests
        if: ${{ success() }}
        run: |
          poetry run pytest --headless --alluredir=reports/allure-results

      - name: Generate Allure report
        if: ${{ success() }}
        run: |
          allure generate reports/allure-results -o reports/allure-report --clean

      - name: Archive Allure report as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: reports/allure-report
